### ISSUE TITLE
Sign In Broken

### ISSUE THREAD

**Issue by evanplaice** [webcomponents-dev/webcomponents.dev#11]
**Describe the bug**
Sign in appears to be broken. Console.log displays errors coming from Firebase

**To Reproduce**
1. Click 'Sign In'
2. Navigate to 'Open Studio'

**Expected behavior**
Should sign in as normal and allow access to my account.

**Screencast**
[WCD Can't Login](https://youtu.be/xeSuHAW6MyY)

**Device**
 - OS: ElementaryOS
 - Browser: Chromium 
 - Version: 78.0.3904.108 (Official Build)

**Additional context**

**Comment by georges-gomes** [comment]
Hi!

I don't have access to ElementaryOS but when I try on MacOS Chromium 80 it does not behave like that.

`Empty cache and Hard reload` is not supposed to log you out.
Only if you delete the cookies and data of the site.
Maybe the cookies and data are a little bit messed up.

If you are stuck, you try clearing all cookies and data.
Then reload and sign-in - you should be prompted with Github password again.

FYI [OPEN STUDIO] button is a shortcut to `https://webcomponents.dev/user/evanplaice` (in your case).

Let me know how it goes
Thanks
Georges

**Comment by evanplaice** [comment]
Checked again today and all is well. Thank you :+1:

**Comment by evanplaice** [comment]
I forgot to mention. For future reference, ElementaryOS is pretty much an Ubuntu base with a nicer GUI shell. Whatever works on Ubuntu will work on Elementary.

**Comment by georges-gomes** [comment]
Good to know as we have access to Ubuntu 👍
