### ISSUE TITLE
License not reflected in the NPM tab

### ISSUE THREAD

**Issue by evanplaice** [webcomponents-dev/webcomponents.dev#12]
**Describe the bug**

When the license is changed in the project info tab, the change isn't reflected in the npm publish tab.

**To Reproduce**
1. Go to project info tab
2. Change license to MIT
3. Go to the npm tab
4. See ISC under license

**Screenshots**

![issue screenshot 1](https://user-images.githubusercontent.com/303159/71042148-33190280-20e8-11ea-9145-626d98f2875c.png)

![issue screenshot 2](https://user-images.githubusercontent.com/303159/71042157-357b5c80-20e8-11ea-93f9-3fc6a72b11b1.png)

**Device**
 - OS: Elementary-OS Juno
 - Browser: Chromium 
 - Version: Version 79.0.3945.79 (Official Build)

**Comment by gqio** [comment]
Hi Evan,

Many thanks for reporting the issue.
Should be fixed. I'm deploying right now

Best,

**Comment by gqio** [comment]
You may need to clean your local cache (in 5-6 min)

Best,
