### ISSUE TITLE
Index.html?

### ISSUE THREAD

**Issue by evanplaice** [webcomponents-dev/webcomponents.dev#13]
**Is your feature request related to a problem? Please describe.**

No problem

**Describe the solution you'd like**

I'd like to replace all the existing demos on [vanillawc][https://github.com/vanillawc] with WCD versions.

To accomplish that, I need a way to load a 3rd-party modules/styles from a CDN (ex jsDelivr); ideally via HTML `<script>` and `<link>` tags.

Is this possible using the current capabilities of webcomponents.dev. If not, could this be made available?

**Comment by gluck** [comment]
Hi Evan,

you can definitely use http links/imports in various places:
- inside `index.js` (or any JS/TS file), you can directly import browser-ESM http URLs
- in an HTML demo, you can use any `<script>` / `<link>` tag

As an exercise I tried pulling some vanillawc demos, and there are a few quirks I can warn you about though:
- we don't currently process unsupported files, so while you can create `.sample` or `.svg` files in the IDE, they won't be available/served in the workshop/html (you can workaround that by using `.html` files)
- `.json` files gets output in a weird path (`dist/src/foo.json`) -> will get fixed

That being said, have a look at [wc-sortable-table](https://webcomponents.dev/edit/Jm5doEIUqJz1d8w9SwSw).

Cheers, and feel free to followup either here or on [twitter](https://twitter.com/Gluckies)/slack, would be glad to hear about your experience.

**Comment by evanplaice** [comment]
Thank you. I'm starting to get a feel for the tool.

While your sample project works great for wc-sortable-table, some of the web components in my collection span hundreds of files. I imagined using it in a much more limited fashion, specifically for demoing purposes. That means, no need for README, index.js, or testing. Only stories and assets are necessary.

Here's another example to demonstrate what I mean [wc-sortable-table](https://webcomponents.dev/edit/e9ymso9FS3XKUVomG90u)

Using ES module imports for JS should work for most things. I can probably find a way to side-load external CSS external styles  (ex prismjs highlighting in wc-markdown). CSV files seem to work without issue.

Don't worry about sample files, that's a made-up extension that is only necessary for my current demo loader. Ideally, I'd like to replace all of my current demos with WebComponents.dev.

**Comment by evanplaice** [comment]
OK, confirmed, Loading an external stylesheet via JS works perfectly. Here's an example.

```javascript
document.querySelector('head').insertAdjacentHTML('beforeend', `<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@vanillawc/wc-codemirror@latest/theme/monokai.css" />`);

```
