### ISSUE TITLE
Add Support for Markdown Files

### ISSUE THREAD

**Issue by evanplaice** [webcomponents-dev/webcomponents.dev#14]
**Is your feature request related to a problem? Please describe.**
I can't fetch `*.md` files from the web component

**Describe the solution you'd like**
Add support for the creation of `.md` files to use as samples in the demos.

**Describe alternatives you've considered**
I can give the file an extension that already works (ex `*.html` or `*.csv`) but that could be confusing to users when they try out my WC demos.

**Additional context**
N/A

**Comment by georges-gomes** [comment]
Hi Evan! @evanplaice 
Can you send a non-working example that should how you would ideally have it?
Thanks

**Comment by evanplaice** [comment]
This project can render external markdown files using fetch. I created duplicate `.csv` files of the markdown files that don't load.

**Comment by georges-gomes** [comment]
It's fixed now 🎉

**IMPORTANT NOTE**: It only works for the newly created `.md` files. So in your example you have to delete the `.md` files and recreate them. Then you will access them like the `.csv` or any other file 👍
