### ISSUE TITLE
Allow Removal of `index.js`

### ISSUE THREAD

**Issue by evanplaice** [webcomponents-dev/webcomponents.dev#15]
**Is your feature request related to a problem? Please describe.**
No problem

**Describe the solution you'd like**
I use WebComponents.dev primarily to demo existing web component libs so I don't need the `index.js` file. The ability to remove it would make the demo setup a little cleaner.

**Describe alternatives you've considered**
Leaving it as is.

**Additional context**
N/A

**Comment by georges-gomes** [comment]
Hi Evan! @evanplaice 
Can you please send a link to an example so we can see how it could look like.
Thanks

**Comment by evanplaice** [comment]
This project has a bunch of files, removing `index.js` would clean things up a bit.

https://webcomponents.dev/edit/FxoojbLdYqBJVJj4Tsex

**Comment by georges-gomes** [comment]
@evanplaice sorry for the delay but we had some dependencies on this one.
It's all good now, you can remove any files, even the `index.js` 😉
