### ISSUE TITLE
Code panel cannot scroll all the way when terminal is opened

### ISSUE THREAD

**Issue by LarsDenBakker** [webcomponents-dev/webcomponents.dev#17]
**Describe the bug**
When the terminal is opened, I can't scroll the code panel all the way to the bottom.

**To Reproduce**
1. Create a new project
2. Ensure there is enough code to scroll
3. Open the terminal
4. You can't scroll to the bottom

**Expected behavior**
You can scroll to the bottom

**Device**
 - OS: Mac OS
 - Browser: Chrome
 - Version: 80

**Comment by georges-gomes** [comment]
Hi Lars
I just tested 
79 works and 80 fails.
I will look at what Chrome did wrong 😛 
Thanks for reporting.

**Comment by Danny-Engelman** [comment]
Maybe https://blog.chromium.org/2020/02/samesite-cookie-changes-in-february.html

**Comment by georges-gomes** [comment]
@LarsDenBakker it's fixed now. The layout of Monaco was not working. My new implementation is actually better and it improves the mobile experience as well.
Please confirm it's good on your side when you have a minute.
Thanks again for reporting 👍
