### ISSUE TITLE
Typo: Loren Ipsum -> Lorem Ipsum

### ISSUE THREAD

**Issue by usergenic** [webcomponents-dev/webcomponents.dev#19]
**Describe the bug**
I generated an ES module with TypeScript and I noticed a small typo.  Pictured here.

**To Reproduce**
1. Generate an ES module with TypeScript.
2. Look at screen.

**Expected behavior**
Lorem Ipsum

**Screenshots**

<img width="1304" alt="Screen Shot 2020-03-11 at 2 45 42 PM" src="https://user-images.githubusercontent.com/578/76467597-2cc4ba80-63a7-11ea-8734-3c409dcf4ee8.png">

**Device**
 - OS: Mac Catalina 
 - Browser: Chrome
 - Version: Really shouldn't matter

**Additional context**
Cool site!

**Comment by georges-gomes** [comment]
Thanks for taking the time to report.
Both ES module template have been updated 👍
