### ISSUE TITLE
Add a library

### ISSUE THREAD

**Issue by lastmjs** [webcomponents-dev/webcomponents.dev#2]
Hey, do you take library requests? I've been working on Functional Element: https://github.com/lastmjs/functional-element

**Comment by georges-gomes** [comment]
We would love to! Just provide a few demos and we do the rest!

**Comment by georges-gomes** [comment]
There is actually already a few demos on the github. We can work with that! Bare with us.

**Comment by georges-gomes** [comment]
Do you have a logo?

**Comment by lastmjs** [comment]
Not yet

**Comment by georges-gomes** [comment]
I made a quick one as a placeholder

<img width="250" alt="image" src="https://user-images.githubusercontent.com/5250572/60545284-04b29100-9d1b-11e9-900e-c0fa2d0118fa.png">

**Comment by gqio** [comment]
Love it :) I had the same idea in mind with the fn math notation

**Comment by georges-gomes** [comment]
One problem with functional-element, we need a transpile js version on npm to import them
Can you make a /dist/functional-element.js transpiled? and reference it in your package.json.
Let me know if you need assistance with this.

**Comment by lastmjs** [comment]
Sweet logo! I can do that, hopefully tonight if not tomorrow

**Comment by georges-gomes** [comment]
Hi @lastmjs 
Any progress on your side?
Thanks

**Comment by georges-gomes** [comment]
Closing for now - don't hesitate to reopen when you see fit.
Cheers

**Comment by lastmjs** [comment]
Hey, so I've pretty much decided to deprecate functional-element. I've been experimenting with it in a larger project, and I just don't think it provides the benefits I was hoping it would. I feel like it's leading my code to be more confusing and complex that using the standard classes of the custom elements API. It was a good experiment, but in the end I think I haven't found the functional solution I want yet

**Comment by lastmjs** [comment]
Sheesh, I'm sorry for not following through on my word for so long, thanks for everything so far

**Comment by georges-gomes** [comment]
No problem Jordan! Any time :+1:
