### ISSUE TITLE
Fetch no longer works

### ISSUE THREAD

**Issue by evanplaice** [webcomponents-dev/webcomponents.dev#20]
**Describe the bug**
Web Components can no longer fetch

**To Reproduce**
1. Go to https://webcomponents.dev/edit/f9IfeJX878gJZibfBcPO?sv=1&pm=1

**Expected behavior**
The Web Component should fetch the file contents and display it in a table.

**Device**
 - OS: ElementaryOS (Ie Ubuntu 18 base)
 - Browser: Chrome (v79.0.3945.88), Chromium (v83.0.4103.97), FireFox (v77.0.1)

**Additional context**
This no longer works for any of my web components that use fetch. Is fetching from a file no longer available as an option or is this a bug?

This applies to all of the Vanilla Web Components collection. The expected behavior has been verified to work outside of the WCD context.

**Comment by gqio** [comment]
Hi Evan,

Sorry for inconvenience and the delay,
Thanks for reporting this issue.

A fix has been merged.
Release is in progress.

Best

**Comment by gqio** [comment]
Hi Evan,

just for letting you know, the fix has been released.

Thanks
