### ISSUE TITLE
So UI in search overlay.

### ISSUE THREAD

**Issue by Westbrook** [webcomponents-dev/webcomponents.dev#21]
**Describe the bug**
When the search UI is open, the close button is not visible...

**To Reproduce**
1. Open your project
2. `command + f`
3. See a search UI with no buttons.

**Expected behavior**
There should be a couple of buttons and some helper text, when comparing to VS Code, at least.

**Screenshots**
![image](https://user-images.githubusercontent.com/1156657/92405703-2ae47580-f104-11ea-91d3-5c01c62b4042.png)

**Device**
 - OS: MacOS
 - Browser: Chrome
 - Version: latest

**Comment by gqio** [comment]
Hi,

Many thanks for reporting this.
Sorry automatic close when merged
Cause of the bug was a CSS issue on our side.

Release tomorrow 🤞 
Thanks
