### ISSUE TITLE
Prettier overrides are not respected until opened and applied again

### ISSUE THREAD

**Issue by bheston** [webcomponents-dev/webcomponents.dev#24]
**Describe the bug**
My project has an override for Prettier settings adjusting `printWidth` wider. This worked after initially applying it, but if I reload the project or come back to it another day, any subsequent change applies the default formatting.

**To Reproduce**
Have a TypeScript project.
Save a file with a long line like
```
import { FASTRadio, FASTRadioGroup, FASTSlider, FASTSwitch } from "@microsoft/fast-components";
```
Save and see it format to multiple lines.
Open prettier settings and set
```
{
  "printWidth": 150
}
```
Go back to your test file and save and see it format as one line.
Close or refresh your browser tab
Open the file and make a change and save it.
Observe it format as multiple lines again.

**Expected behavior**
Expected the Prettier configuration to be used by default.

**Device**
 - OS: Windows
 - Browser: Edge
 - Version: 87.0.634.0 (Canary)

**Comment by georges-gomes** [comment]
Thanks for reporting, very annoying indeed!
On it 👍

**Comment by gqio** [comment]
Hi,

Fix done, release on the way

Thanks.

**Comment by gqio** [comment]
Should be working right now, please let me know if you encounter any issue.

Thanks @bheston

**Comment by bheston** [comment]
Just went back into a project and it worked! Thanks for the quick turnaround @gqio!
