### ISSUE TITLE
Publishing a component fails

### ISSUE THREAD

**Issue by J0ne** [webcomponents-dev/webcomponents.dev#25]
When trying to dry-run or publish the server responses status code 500: 
{"error":{"message":"INTERNAL","status":"INTERNAL"}}

And the actual end point (https://us-central1-prd-webcomponents-editor.cloudfunctions.net/publishPackage)
responses 400
{"error":{"message":"Bad Request","status":"INVALID_ARGUMENT"}}

**To Reproduce**
Try dry-run/publish with an old component (or start building a new one and then dry-run)

**Expected behavior**
Component is published in NPM

**Screenshots**
![image](https://user-images.githubusercontent.com/671343/93048566-da22ce80-f667-11ea-8d87-fece81ea8c5e.png)
![image](https://user-images.githubusercontent.com/671343/93048641-00e10500-f668-11ea-9cb2-18d521a62392.png)
![image](https://user-images.githubusercontent.com/671343/93048702-28d06880-f668-11ea-9d02-77de30b235cf.png)
![image](https://user-images.githubusercontent.com/671343/93048719-32f26700-f668-11ea-9ed4-2be9751cf5e9.png)

**Device**
 - OS: Mac OS / Windows
 - Browser: Chrome
 - Version: latest

**Comment by gqio** [comment]
Hi,

Many thanks for reporting this issue.
We are on it.

I will let you know when it's fixed.

Thanks

**Comment by gqio** [comment]
Fix done, release in progress

**Comment by J0ne** [comment]
Thank you very much!

**Comment by gqio** [comment]
Should be good in 20min 🤞

**Comment by J0ne** [comment]
Yeah, it works!

**Comment by gqio** [comment]
> Yeah, it works!

Truly sorry, a tiny bug is still present but on its way to be released, 

Your component was not prefixed by your username at publish time.

for instance your component has been published as `@wcd/componentName` but should have been `@wcd/username.componentName` you should experience at the next release of your component a rename of the package.

Sorry for the inconvenience

**Comment by J0ne** [comment]
Yes, actually noticed that a bit later. But no serious harm done. No problem at all.
The component is just for demoing and work in progress... 
Is it possible to delete the package from @wcd namespace?

**Comment by gqio** [comment]
Sadly no,

We are using a free public scope for npmjs (@wcd) for the Free plan, and like any other free scope on npmjs, you can't unpublished except in the window of 72h, and we didn't implemented the unpublish in the platform for the full scope of @wcd

But with an Enthusiast membership on our platform, you will be able to have a customisable public/private registry and custom public/private scope configuration, like Github Packages for instance, you will have a complete control over your public and private packages published.

Additionally you can sync to private repository your components ;)

Best.
