### ISSUE TITLE
Turn off useDefineForClassFields in tsconfig

### ISSUE THREAD

**Issue by justinfagnani** [webcomponents-dev/webcomponents.dev#27]
**Describe the bug**

The useDefineForClassFields option breaks decorators. See https://github.com/Polymer/lit-element/issues/1085#issuecomment-705679496 (which has a webcomponents.dev example) and https://github.com/microsoft/TypeScript/issues/35081

**To Reproduce**
1. Create a TypeScript LitElement
2. Define a property with `@property`
3. Set the property to a new value
4. Component doesn't update

**Expected behavior**
Component updates

Ideally all the settings in tsconfig would be exposed so users can fix problems like this on their own too.

**Comment by georges-gomes** [comment]
Hi @justinfagnani, thanks for taking the time to report. It seems that we don't set useDefineForClassFields but @gluck is looking into the issues you pointed to solve it.

**Comment by georges-gomes** [comment]
(We are doing some ground work right now that will allow us to expose tsconfig 👍)

**Comment by gluck** [comment]
Hi @justinfagnani 

while tuning `tsconfig.json` is on our radar indeed, turning off the flag seems risky:
- potential impact on other frameworks
- no feedback from the TS team as whether they plan to change the behavior or not ?

In the meantime you can switch fro the TS compiler to Babel, which seems to mitigate this issue somehow ?
You can probably explain that behavior, but using babel with the plugins:
```
    [ "proposal-decorators", { "legacy": true } ],
    [ "proposal-class-properties", { "loose": true } ]
```
The component still fails: https://webcomponents.dev/edit/jqCnCK2ELPT7WU6sKlVd
(This seems unexpected in regards to comment [here](https://github.com/microsoft/TypeScript/issues/35081#issuecomment-608140969))

While if you retain the decorator, it works: https://webcomponents.dev/edit/e9q8cMR1ZrhkZMrUBHdN
```
    [ "proposal-decorators", { "decoratorsBeforeExport": true } ],
    [ "proposal-class-properties", { } ]
```
 
You can tune babelrc here (once you fork the component) :
![image](https://user-images.githubusercontent.com/604263/95584493-2205fd00-0a3e-11eb-8e45-96db44e56856.png)

Let us know what you think.

**Comment by justinfagnani** [comment]
@gluck 

> while tuning tsconfig.json is on our radar indeed, turning off the flag seems risky:

The flag is off by default. It breaks existing code and it completely breaks LitElement with decorators. It's really experimental and not viable yet, so it shouldn't be turned on in the first place. I'm not aware of any way in which it would effect other frameworks.

**Comment by justinfagnani** [comment]
I'm pretty sure that `useDefineForClassFields` is still false by default. It's not mentioned in any release notes as being set to true, and the TypeScript playground has it off by default: https://www.typescriptlang.org/play?#code/MYGwhgzhAECC0G8BQ1pgFzQgFwE4EsA7Ac2gF5oByMSgbiQF8g

**Comment by georges-gomes** [comment]
Hi @justinfagnani 

The live demo reported in https://github.com/Polymer/lit-element/issues/1085#issue-717451445 is using a `index.js` file from a `js` template. Typescript not involved (only babel). 

Renaming the file to `index.ts` Typescript is involved and everything is 👍
See here https://webcomponents.dev/edit/M8bj15ZDd1MKHsJeT1Vl

**Comment by georges-gomes** [comment]
But we learn that babel with  
```
 [ "proposal-decorators", { "legacy": true } ],
 [ "proposal-class-properties", { "loose": true } ]
```
currently fails

**Comment by georges-gomes** [comment]
I'm closing this issue as `useDefineForClassFields` is not set to `true`.
We will follow up on https://github.com/Polymer/lit-element/issues/1085 to see if we need to open another issue for babel decorators and LitElement on the platform.
Thanks all 👍
