### ISSUE TITLE
[feature]: file tree

### ISSUE THREAD

**Issue by bennypowers** [webcomponents-dev/webcomponents.dev#28]
It would be extremely useful to have a file tree a la codesandbox:

<img width="280" alt="Screen Shot 2020-11-28 at 18 42 36" src="https://user-images.githubusercontent.com/1466420/100520962-81b09700-31a9-11eb-9968-c40932e34632.png">

This would help with
- discoverability (Really? I can delete files?)
- maintenance (Where did I write that snippet?)
- customizablility (babel, eslint config etc)

**Comment by georges-gomes** [comment]
You can configure `babel` and `eslint` (when we support it) in the config "folder"

<img width="157" alt="image" src="https://user-images.githubusercontent.com/5250572/100522602-a1948a80-31aa-11eb-9e6e-1b5fa5951128.png">

**Comment by georges-gomes** [comment]
I understand some of the benefits of the file tree but it's not a silver bullet.

Let me highlight some of the benefits of our approach:

<img width="236" alt="image" src="https://user-images.githubusercontent.com/5250572/100522743-78c0c500-31ab-11eb-94f3-d81d17d08711.png">

1) It takes a lot less screen space

2) When you switch between `Code`, `Website` and `Config`, only the files of the right context appear. This helps focusing to the task you are doing.

3) When switch back an forth between `Code` and `Website`, the previous selected file is remembered so you don't look for the right file.

We are still missing a ton of keyboard shortcut but we see some benefits in this approach down the line.

**This been said, we will probably have a file tree option at some point and let users choose. Makes a lot of sense. 👍**

**Comment by bennypowers** [comment]
Yes your approach is elegant

Most users will be used to the file tree though, and will be confused by innovative UIs

Having it toggleable in user preferences would be a wonderful solution.

**Comment by georges-gomes** [comment]
File tree delivered 🎉
Thanks for rising this to our attention @bennypowers !
Cheers
