### ISSUE TITLE
[feature]: Turn off prettier

### ISSUE THREAD

**Issue by bennypowers** [webcomponents-dev/webcomponents.dev#29]
Some people like Prettier a lot.

Other people can't stand it one bit.

Can you guess which category I fall into? 😉 

It would be great to be able to configure things like prettier and eslint per project. see #28

**Comment by georges-gomes** [comment]
You can select this "folder"

<img width="157" alt="image" src="https://user-images.githubusercontent.com/5250572/100522329-23d07f00-31aa-
11eb-9f66-7d04ede136c7.png">

and add config files like `.prettierrc`

You want `Prettier` completely off?

Some details 
https://webcomponents.dev/docs/folder-config/

**Comment by bennypowers** [comment]
Yeah I get most of the benefits of prettier from `@pwrs/eslint-config`, and as far as template formatting goes, I'll suffer less doing it myself than I would looking at how Prettier mangles my code 😉

**Comment by bennypowers** [comment]
see also #28

**Comment by georges-gomes** [comment]
I see.

Can I rename this issue "[feature]: Turn off prettier" ?

**Comment by bennypowers** [comment]
Yes, but that would not cover the "use eslint" or "use web-dev-server config" cases

**Comment by georges-gomes** [comment]
I created #31 

I guess "use web-dev-server config" means using [this](https://modern-web.dev/docs/dev-server/cli-and-configuration/#configuration-file).

But we don't use `web-dev-server`... would be hard for us to keep up.

**Comment by georges-gomes** [comment]
Delivered. 🎉

Prettier is off by default now and you can add it configuration.

https://webcomponents.dev/docs/prettier/

Thanks @bennypowers for reporting

**Comment by bennypowers** [comment]
Killer. Well done
