### ISSUE TITLE
Preact example gives errors

### ISSUE THREAD

**Issue by bahrus** [webcomponents-dev/webcomponents.dev#3]
**Describe the bug**
Great site.  If I click on the preact example, I get errors

Uncaught TypeError: Failed to resolve module specifier "preact". Relative references must start with either "/", "./", or "../". 
Uncaught TypeError: Failed to resolve module specifier "preact". Relative references must start with eith

**To Reproduce**
1. Go to https://webcomponents.dev/
2. Click on Preact Element
3. See error

**Expected behavior**
I would expect to see some meaningful UI element

**Device**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 76 (I don't have many experimental flags set).

**Comment by georges-gomes** [comment]
Hi Bruce @bahrus 

Thank you very much for taking the time to report the issue 👍

I temporary fixed the template by adding `import 'preact';`
It was previous a dependency of `html/preact` I think and it may have changed.
We need more analysis...

I leave it open, @gluck will probably have a look at it when he is back from holiday.

Thanks again for reporting 🙏

**Comment by gluck** [comment]
Yes, htm has [removed](https://github.com/developit/htm/issues/94) the preact peer dependency at root level (for good reason, as htm can be used with other fwks).
Adding it explicitly is the correct way to go.

**Comment by georges-gomes** [comment]
Way to go it is!
Thanks again @bahrus for reporting 👍
