### ISSUE TITLE
Can't preview LWC projects

### ISSUE THREAD

**Issue by wrone** [webcomponents-dev/webcomponents.dev#34]
**Describe the bug**
Preview doesn't work, I tried the default LWC project, tried to delete everything and write my own code - no luck.

**To Reproduce**
1. Select a new LWC project

**Expected behavior**
Should be able to preview the component

**Screenshots**
![image](https://user-images.githubusercontent.com/9321029/102540195-5984cb80-40b7-11eb-9bc9-b803f97fff31.png)
![image](https://user-images.githubusercontent.com/9321029/102540760-2bec5200-40b8-11eb-8349-5a53ac81ab9f.png)

**Device**
 - OS: Windows 10
 - Browser: Firefox 
 - Version: 83.0 (64-bit)

**Comment by wrone** [comment]
Just checked in Chrome, it works there!

**Comment by gqio** [comment]
Hi, I am Greg, part of the webcomponents.dev team.

Are you using firefox in anonymous mode ? Because we have issue with no service worker available in Firefox when anonymous is enabled, but works with chromium family browsers

Best,

**Comment by wrone** [comment]
Nope, it was a normal session, not anonymous.

**Comment by georges-gomes** [comment]
We think it was a timeout on our side.
Can you try again now please ?

**Comment by wrone** [comment]
It works now in Firefox, but I'm on a different machine right now, not sure if it is important, I can test again later this evening

**Comment by gqio** [comment]
Hi @wrone ,

I close this issue since it seems you are able to compile and run your component, please reopen if needed

Thanks.
