### ISSUE TITLE
Fail to use dynamic import

### ISSUE THREAD

**Issue by motss** [webcomponents-dev/webcomponents.dev#35]
## Describe the bug

Unable to use `import(url)` to dynamically import a file.

## To Reproduce
1. Go to https://webcomponents.dev/edit/xp7U9qVlD7gEyYPC8Ykc
2. Fail to load due to `import(url)` syntax

## Expected behavior

Able to dynamic import file.

## Screenshots

NA

**Device**
 - OS: NA
 - Browser: Edge
 - Version: 89

**Additional context**

**Comment by georges-gomes** [comment]
Indeed we don't support this use case. We will look into it.
Thanks for reporting 👍

**Comment by motss** [comment]
That's sad. I was spending hours on this to figure out what I did wrongly. I was expecting everything native is supported. 😥

**Comment by gqio** [comment]
Hi, I may have a (good?) news for you

Please check this one:
https://webcomponents.dev/edit/EXnLyGY2G0bLEw1ZyMBh

You can import dynamically, but we do not support as of today the `import.meta.url` directly in the stories (mostly due to one tiny bug in our parser but will be fixed soon, stay tuned ;))

Hope it helps.

Best.

**Comment by motss** [comment]
@gqio Thanks for the suggestion. Apparently I overlooked on this one. It seems like it only works if you import a static URL, like so:

```ts
import('./other-app.js'); // This works

const fileUrl = './other-app.js';
import(fileUrl); // This does not work
```

**Comment by gqio** [comment]
yes you are right, the parser does not understand yet variables

**Comment by gqio** [comment]
Hi @motss ,

Sorry for the auto close of GitHub for this issue :( 
I just released a version supporting dynamic import with variables

Here you can find a working version : https://webcomponents.dev/edit/EXnLyGY2G0bLEw1ZyMBh

Thanks
