### ISSUE TITLE
website: on hover weird effect with Safari

### ISSUE THREAD

**Issue by peterpeterparker** [webcomponents-dev/webcomponents.dev#4]
**Describe the bug**

Hi,

So maybe it's just me, if it's the case, please apologize, but there is a weird effect with the on hover effect of your components selection of your website.

It seems that it happens only with Safari.

**To Reproduce**
1. Open https://webcomponents.dev in Safari
2. Mouse -> components -> on hover

**Screenshots**

<img width="1346" alt="Capture d’écran 2019-09-06 à 16 55 54" src="https://user-images.githubusercontent.com/16886711/64438051-b083ae80-d0c7-11e9-8af0-0bbf63097b8e.png">
<img width="1346" alt="Capture d’écran 2019-09-06 à 16 56 06" src="https://user-images.githubusercontent.com/16886711/64438052-b083ae80-d0c7-11e9-8547-b1c3ee80074a.png">
<img width="1346" alt="Capture d’écran 2019-09-06 à 16 56 08" src="https://user-images.githubusercontent.com/16886711/64438053-b083ae80-d0c7-11e9-9902-f4d71ff7361a.png">

**Device**
OSX

**Comment by gqio** [comment]
Hi David,

Many thanks for pointing this out.
We are on it.

Thanks

**Comment by georges-gomes** [comment]
Thanks @peterpeterparker for taking the time to report 🙏
Fixed now

**Comment by gqio** [comment]
Hi David,

Just to keep you posted,
We have corrected and deployed the fix in production.
You could see the difference now.

Many thanks for your feedback.
Best

**Comment by peterpeterparker** [comment]
Awesome, well done @gqio and @georges-gomes, that was super fast 👍 

p.s.: of course I confirm that it is now fixed
