### ISSUE TITLE
Error publishing to NPM

### ISSUE THREAD

**Issue by MarkJamesHoward** [webcomponents-dev/webcomponents.dev#41]
**Describe the bug**
When attempting to publish to npm I'm seeing the error as below:

Error: Error: name field must be a string.

**To Reproduce**
1. Go to NPM tab
2. Click on 'Publish'

**Expected behavior**
Publishes to NPM successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/11471648/104248997-730b0e80-54cf-11eb-86d1-908c9111392e.png)

**Device**
 - OS:  Windows 19
 - Browser:  Chrome
 - Version:  87

I'm wondering if this is needed to be setup in the package.json, but then I can't access it I think?

Thanks
Mark

**Comment by gqio** [comment]
Hi @MarkJamesHoward ,

Many thanks for reporting this.
I was able to reproduce.
During a big upgrade of dependencies we updated accidentally a lib we are using for publishing to npm.
I reverted to the stable version. Release is under way.

Please reopen the ticket if you experience any issue

Thanks
Have a good day
