### ISSUE TITLE
Error loading demos

### ISSUE THREAD

**Issue by bennypowers** [webcomponents-dev/webcomponents.dev#42]
**Describe the bug**
Component demos are not loading modules

**To Reproduce**
1. https://webcomponents.dev/create/litelement+ts

**Expected behavior**
Everything works as normal

**Screenshots**
<img width="1281" alt="Screen Shot 2021-01-15 at 13 40 13" src="https://user-images.githubusercontent.com/1466420/104723031-4c4f1100-5737-11eb-8e35-72341929e392.png">

**Comment by gqio** [comment]
Hi,

We delivered at noon our dependency service with apparently a bug,
it has been fixed and released.

Thanks for reporting this.

Best
