### ISSUE TITLE
package.json / dependency management

### ISSUE THREAD

**Issue by bennypowers** [webcomponents-dev/webcomponents.dev#43]
**Describe the bug**
Currently, the only way to manage dependencies is with `import` statements. If I want to use a particular version I have to `import '@scope/package@tag-or-version;`, which is clumsy and error prone. In addition, it's not clear from a user's point of view how that interacts with the cache, and often times so-imported dependencies give an error underline, even if they have been cached.

**Expected behavior**
Instead, give users control over package.json, so we can define dependencies directly.

**Comment by gqio** [comment]
Hi @bennypowers ,

We are currently working on it ;)
Will be release I hope soon.

Thanks for reporting it.

Have a good day

**Comment by bennypowers** [comment]
I know you are :D

Some other features came up in chat recently, and I saw this one wasn't publicly tracked, so I though it would be good to open a quick issue so everyone know's it's in development.

This is going to be *huge*

TY

**Comment by georges-gomes** [comment]
Hi @bennypowers , we just silently released a major upgrade with support of `package.json`
Here is the documentation https://webcomponents.dev/docs/package.json/
Please let us know what you think 🙏
Good weekend and Thanks!
