### ISSUE TITLE
Be able to share a specific line of code via url

### ISSUE THREAD

**Issue by FabienTaillon** [webcomponents-dev/webcomponents.dev#46]
Like what can be done in GitHub, it would be cool to be able to share via url a specific line of code.

**Comment by georges-gomes** [comment]
That's actually a very good idea! Let's see how best we can do that 👍

**Comment by FabienTaillon** [comment]
Why is it closed ?

**Comment by georges-gomes** [comment]
Hi @FabienTaillon 
Closed by mistake because linked internally :)
We are releasing in the next few hours 😉
I will let you know.

Side note: are you on discord? I would like to quickly chat with you if you don't mind.

Cheers
Georges

**Comment by georges-gomes** [comment]
Released by @gluck ! 
Add `#L22` to the URL to highlight line 22
Add `#L22-L45` to the URL to highlight line 22-to-45

Thanks @FabienTaillon for the request 👍

**Comment by FabienTaillon** [comment]
@georges-gomes Cool ! I'm not a big discord user even though I connect from time to time ^^
My username seems to be FabienTaillon#4253 if I'm correct.
