### ISSUE TITLE
"Request a feature" opens a "Bug report" instead of a "Feature request"

### ISSUE THREAD

**Issue by FabienTaillon** [webcomponents-dev/webcomponents.dev#47]
**Describe the bug**
While clicking on the "Request a feature" button, a new issue page is open on GitHub, but using the "Bug report" template instead of the "Feature request" one.

**To Reproduce**
* Click on the "Feedback" button
* Click on "Request a feature"

**Expected behavior**
An new issue page with the "Feature request" template is open.

**Screenshots**
<img width="198" alt="feature" src="https://user-images.githubusercontent.com/2465122/108483409-ff60dc00-729a-11eb-94bc-34d033932a31.png">

**Comment by georges-gomes** [comment]
Hi @FabienTaillon, this has been fixed.
Thanks for reporting 👍
