### ISSUE TITLE
Deploy to GitHub Pages: TypeError: U.find is not a function

### ISSUE THREAD

**Issue by goaround** [webcomponents-dev/webcomponents.dev#49]
**Describe the bug**

When I try to deploy to GitHub Pages I get an TypeError: U.find is not a function.

**To Reproduce**
1. Deploy to GitHub Pages
2. See error

**Expected behavior**
No Error

**Screenshots**

![grafik](https://user-images.githubusercontent.com/5927337/117142952-97596680-adb0-11eb-9400-ddf34f04cce7.png)

**Device**
 - OS: MacOS
 - Browser: Firefox 
 - Version: 88.0

**Comment by muryoh** [comment]
Should be fixed!
