### ISSUE TITLE
Can't unlock projects for editing under an org I own

### ISSUE THREAD

**Issue by evanplaice** [webcomponents-dev/webcomponents.dev#52]
**Describe the bug**
I (EvanPlaice) can't unlock any of I own for editing projects under an org I own (VanillaWC)

**To Reproduce**
1. Login
2. GoTo VanillaWC org
3. Select a component
4. Goto Settings
5. The lock icon is greyed out

**Expected behavior**
The lock icon shouldn't be greyed out when I'm logged in because I own the org

**Screenshots**

**Device**
 - OS: OSX Mojave
 - Browser: Brave (Chromium Based)

**Comment by gqio** [comment]
Hi @evanplaice 

Sorry for the inconvenience.

Could you please share a link to the component ?

Thanks

**Comment by evanplaice** [comment]
No worries, it's all of the components under the VanillaWC org

Here's a link to one of them:
https://webcomponents.dev/edit/FxoojbLdYqBJVJj4Tsex/src/index.stories.js?sv=1&pm=1

**Comment by gqio** [comment]
On it.

I will keep you posted

**Comment by gqio** [comment]
Hi,

Found the issue.
Fix done.
Release in progress

Should be available in 5min

**Comment by gqio** [comment]
Feel free to reopen it if you encounter any issue
