### ISSUE TITLE
how to edit the example code in webcomponents.dev?

### ISSUE THREAD

**Issue by minalonthego** [webcomponents-dev/webcomponents.dev#53]
I'm getting a pop-up saying "cannot edit in read-only editor"

**Comment by georges-gomes** [comment]
If it's the component of someone else you need to first [ fork ] with the button in header.

If it's your component, when you connect it to Github/Gitlab then main/master branch is readonly.
You must create a branch to make changes.

If you are in either of these cases, please send a link to your component, we have a look.

**Comment by georges-gomes** [comment]
Let us know if you need any more help
Thanks
