### ISSUE TITLE
Safari 13 incompatibility

### ISSUE THREAD

**Issue by peterpeterparker** [webcomponents-dev/webcomponents.dev#6]
**Describe the bug**
I think you've got a problem in the detection of the Safari version. v13 > v12 (see screenshots).

**To Reproduce**
1. Go to http://webcomponents.dev with Safari v13
2. Click on Stencil

**Screenshots**
<img width="1191" alt="Capture d’écran 2019-09-27 à 10 40 21" src="https://user-images.githubusercontent.com/16886711/65755477-7714f080-e113-11e9-98b8-4eb3652fb71c.png">

<img width="1191" alt="Capture d’écran 2019-09-27 à 10 41 17" src="https://user-images.githubusercontent.com/16886711/65755478-7714f080-e113-11e9-9993-9f1ae567b4a5.png">

**Comment by georges-gomes** [comment]
Thanks for taking the time 👍 
Will be fixed in a few minutes.

**Comment by georges-gomes** [comment]
It's fixed. You may be served with a cached version from your browser for 45min. 
To have it faster you can disable cache once via devtools
<img width="1520" alt="image" src="https://user-images.githubusercontent.com/5250572/65762212-c9104300-e120-11e9-965b-e5908ddaf544.png">

**Comment by peterpeterparker** [comment]
it's all good/fixed, well done 👍
