### ISSUE TITLE
npm publish fails silently with Github account with capitalisation

### ISSUE THREAD

**Issue by MarkJamesHoward** [webcomponents-dev/webcomponents.dev#7]
**Describe the bug**
When publishing to npm if your GitHub username contains any capital letters then the publish fails silently. 

**To Reproduce**
1. Create a sample using any of the libraries 
2. Login to Github using an account with capitals (e.g. MarkJamesHoward)
3. publish to npm
4. See error - *well there is no error shown and the publish fails

**Expected behavior**
An error is displayed informing that the account needs to be lower case. Or change the package name to use only lowercase automatically

**Screenshots**

**Device**
 - OS:  Windows
 - Browser:  Chrome 
 - Version: 78

**Comment by gqio** [comment]
Hi Mark,

Apparently you have been able to publish correctly to NPM with the platform.
![image](https://user-images.githubusercontent.com/1063530/69015596-cf3ed500-0995-11ea-8abd-0b36a4bc960c.png)

But you are totally right, we need to fix the link in the NPM publish panel and give more feedback to the user, in case of both success/failure. As of today, In case of failure we are logging everything into the dev console.
Did you experienced any error while publishing ?

Many thanks for your feedback.
Fix is on its way.

Best,

**Comment by gqio** [comment]
Hi Mark,

Fix will be delivered in few minutes
Please do not hesitate to reopen if you encounter any issue.

Many Thanks

**Comment by MarkJamesHoward** [comment]
Thanks @gqio :-)
I did find the error in the dev console yep, and then manually changed my name to have lower case in the UI and the publish succeeded then. 

I'm trying to unpublish those packages from npm as they are just tests - but no luck. I wonder if because they are under the @wcd scope and I don't have permissions?

npm unpublish @wcd/markjameshoward.demo-lit-ts-time-picker-fork-k3231lcc@0.2.0 -f

**Comment by gluck** [comment]
Hi Mark,

indeed you can't unpublish the package as it wasn't published using your npm credentials but ours, we could offer the option to unpublish (within the 72h window of npm) through the interface, didn't think about that use case.

But we can do it for you, I unpublished the 3 versions you pushed if that component.

Publishing to your own npm account/scope is part of pro/entreprise features (beta comming soon, stay tuned).

Cheers.

**Comment by MarkJamesHoward** [comment]
cool sounds good thanks :-)
