### ISSUE TITLE
GitLab Support

### ISSUE THREAD

**Issue by bennypowers** [webcomponents-dev/webcomponents.dev#8]
**Is your feature request related to a problem? Please describe.**
Let's get GitLab support on the road!

**Comment by georges-gomes** [comment]
We are moving the feature requests to Spectrum.
This moved here https://spectrum.chat/webcomponents-dev/feature-requests/gitlab-support~4f0066ec-ae9e-4c40-b54e-d9cce27e0ca5

Thanks!
